version: '3.8'

services:
  google-wallet-app:
    build: .
    container_name: google-wallet-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env
    volumes:
      # Mount the app directory for development (optional)
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - wallet-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  wallet-network:
    driver: bridge

# Optional: Add a volume for persistent data if needed
volumes:
  app_data:
    driver: local
